# Generated by Django 2.1.7 on 2019-03-03 15:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_auto_20190222_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicsubscription',
            name='interest',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='topicsubscription',
            name='knowlage',
            field=models.PositiveSmallIntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='topicsubscription',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribtion', to='topics.Topic'),
        ),
    ]
