# Generated by Django 2.1.7 on 2019-04-06 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_userfollowersbridge_followers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
