# Generated by Django 2.1.7 on 2019-03-07 13:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('id', 'user', 'question')},
        ),
    ]
