# Generated by Django 2.1.7 on 2019-04-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190330_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='is_published'),
        ),
    ]
