# Generated by Django 2.1.7 on 2019-04-06 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_answer_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='followquestion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='creation date and time'),
            preserve_default=False,
        ),
    ]
